# Generated by Django 5.2.13 on 2026-04-20 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("bibliographie", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("isnb", models.CharField(blank=True, max_length=12, unique=True)),
                ("date_publication", models.DateField()),
                ("nombre_exemplaires", models.PositiveIntegerField(default=1)),
                ("resume", models.TextField(max_length=300)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livres",
                        to="ges_catalogue.auteur",
                    ),
                ),
                (
                    "categorie",
                    models.ManyToManyField(
                        blank=True, related_name="livres", to="ges_catalogue.categorie"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateTimeField(auto_now_add=True)),
                ("date_retour_prevue", models.DateField()),
                ("date_retour_reelle", models.DateField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprunts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprunts",
                        to="ges_catalogue.livre",
                    ),
                ),
            ],
        ),
    ]
